---

- name: Ensure keys folder exists locally
  file: path=keys state=directory
  connection: local
  run_once: true
  become: no

- name: Create gaiad user
  user: name=gaiad home=/home/gaiad shell=/bin/bash

- name: Copy gaiad binary
  copy:
    src: "{{BINARY}}"
    dest: /usr/bin/gaiad
    mode: 0755

- name: Copy gaiacli binary
  copy:
    src: "{{GAIACLI_BINARY}}"
    dest: /usr/bin/gaiacli
    mode: 0755

- name: Copy service file
  copy: src=gaiad.service dest=/etc/systemd/system/gaiad.service mode=0755
  notify: reload systemd

#- name: Get node ID
#  command: "cat /etc/nodeid"
#  changed_when: false
#  register: nodeid

- name: Create empty genesis
  command: "/usr/bin/gaiad init --chain-id {{TESTNET_NAME}} --moniker {{inventory_hostname}}"
  become: yes
  become_user: gaiad
  args:
    creates: /home/gaiad/.gaiad/config/genesis.json

- name: Create key password file
  become: yes
  copy:
    content: "1234567890\n"
    dest: /home/gaiad/pwd_val_key
    mode: 0600
    owner: gaiad
    group: gaiad

- name: Create validator key
  shell: "/usr/bin/gaiacli keys add val_key < /home/gaiad/pwd_val_key"
  become: yes
  become_user: gaiad
  args:
    creates: /home/gaiad/.gaiacli/keys

- name: Create initial transaction
  shell: "/usr/bin/gaiad gentx --amount {{AMOUNT}} --name=val_key < /home/gaiad/pwd_val_key"
  become: yes
  become_user: gaiad
  args:
    creates: /home/gaiad/.gaiad/config/gentx

- name: Find gentx file
  command: "ls /home/gaiad/.gaiad/config/gentx"
  changed_when: false
  register: gentxfile

- name: Clear local gen-tx list
  file: path=files/ state=absent
  connection: local
  become: no
  run_once: yes

- name: Get gen-tx file
  fetch:
    dest: files/
    src: "/home/gaiad/.gaiad/config/gentx/{{gentxfile.stdout_lines[0]}}"
    flat: yes

- name: Get genesis.json file
  fetch:
    dest: files/
    src: "/home/gaiad/.gaiad/config/genesis.json"
    flat: yes
  run_once: yes
